// Mock data for frontend-only demo

export const MOCK_EXCHANGE_POSTS = [
  {
    id: "1",
    title: "Drake Concert Tickets - Floor Seats",
    description: "Two floor seats for Drake's upcoming concert. Can't make it anymore, selling at face value!",
    price: 250,
    price_negotiability: "negotiable" as const,
    category: "Concert Tickets" as const,
    poster: "Sarah Johnson",
    rating: 4.8,
    review_count: 12,
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    expires_at: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "2",
    title: "Mini Fridge - Perfect Condition",
    description: "Compact mini fridge, barely used. Great for dorm rooms. Includes freezer compartment.",
    price: 75,
    price_negotiability: "non-negotiable" as const,
    category: "Dorm Items" as const,
    poster: "Mike Chen",
    rating: 5.0,
    review_count: 8,
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    expires_at: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "3",
    title: "Resume Review & Career Coaching",
    description: "Former McKinsey consultant offering resume reviews and interview prep. 1-hour sessions.",
    price: 50,
    price_negotiability: "negotiable" as const,
    category: "Preprofessional Help" as const,
    poster: "Alex Rivera",
    rating: 4.9,
    review_count: 24,
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    expires_at: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "4",
    title: "Chipotle Line Service - Save Time!",
    description: "I'll wait in the Chipotle line for you during lunch rush. Just text me your order!",
    price: 5,
    price_negotiability: "non-negotiable" as const,
    category: "Food Truck Line Service" as const,
    poster: "Jamie Lee",
    rating: 4.7,
    review_count: 31,
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    expires_at: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "5",
    title: "Taylor Swift Eras Tour Tickets",
    description: "Section 204, Row 12. Amazing view! Selling because of family emergency.",
    price: 400,
    price_negotiability: "negotiable" as const,
    category: "Concert Tickets" as const,
    poster: "Emma Davis",
    rating: 4.9,
    review_count: 15,
    created_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    expires_at: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
]

export const MOCK_RIDESHARE_POSTS = [
  {
    id: "1",
    title: "Weekend Trip to NYC",
    description: "Heading to NYC this Saturday morning, returning Sunday evening. Have 3 seats available in my SUV.",
    from_location: "Campus Center",
    destination: "Manhattan, NY",
    departure_time: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    available_seats: 3,
    price_per_person: 40,
    poster: "Chris Martinez",
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "2",
    title: "Airport Run - Early Morning",
    description: "Going to the airport for a 6 AM flight. Can take 2 people with luggage.",
    from_location: "North Dorms",
    destination: "JFK Airport",
    departure_time: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    available_seats: 2,
    price_per_person: 25,
    poster: "Lisa Wang",
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "3",
    title: "Boston Shopping Trip",
    description: "Going to Boston for shopping this weekend. Leaving Saturday at 10 AM, back by 8 PM.",
    from_location: "Student Union",
    destination: "Boston, MA",
    departure_time: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    available_seats: 4,
    price_per_person: 15,
    poster: "Jordan Kim",
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
]

export const MOCK_ACADEMIC_POSTS = [
  {
    id: "1",
    department: "Computer Science",
    course: "CS 101",
    title: "Introduction to Programming - Complete Notes",
    resource: "Lecture Notes",
    pdf_url: "/placeholder.pdf",
    upload_date: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    popularity: 245,
    file_size: 2500000,
    file_type: "application/pdf",
    uploader: "Prof. Anderson",
  },
  {
    id: "2",
    department: "Mathematics",
    course: "MATH 201",
    title: "Calculus II - Practice Problems with Solutions",
    resource: "Practice Problems",
    pdf_url: "/placeholder.pdf",
    upload_date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    popularity: 189,
    file_size: 1800000,
    file_type: "application/pdf",
    uploader: "Study Group A",
  },
  {
    id: "3",
    department: "Biology",
    course: "BIO 150",
    title: "Cell Biology - Midterm Study Guide",
    resource: "Study Guide",
    pdf_url: "/placeholder.pdf",
    upload_date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    popularity: 312,
    file_size: 3200000,
    file_type: "application/pdf",
    uploader: "TA Sarah",
  },
  {
    id: "4",
    department: "Economics",
    course: "ECON 101",
    title: "Microeconomics - Chapter Summaries",
    resource: "Summary",
    pdf_url: "/placeholder.pdf",
    upload_date: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    popularity: 156,
    file_size: 1200000,
    file_type: "application/pdf",
    uploader: "Alex Thompson",
  },
]

export const MOCK_CONVERSATIONS = [
  {
    id: "1",
    other_user: {
      id: "user-2",
      username: "sarah_j",
      full_name: "Sarah Johnson",
    },
    last_message: "Sounds good! See you at 3 PM",
    last_message_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    unread_count: 0,
  },
  {
    id: "2",
    other_user: {
      id: "user-3",
      username: "mike_c",
      full_name: "Mike Chen",
    },
    last_message: "Is the fridge still available?",
    last_message_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    unread_count: 2,
  },
  {
    id: "3",
    other_user: {
      id: "user-4",
      username: "alex_r",
      full_name: "Alex Rivera",
    },
    last_message: "Thanks for the resume tips!",
    last_message_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    unread_count: 0,
  },
]

export const MOCK_MESSAGES = [
  {
    id: "1",
    conversation_id: "1",
    sender_id: "user-2",
    content: "Hi! I'm interested in the concert tickets",
    created_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    is_read: true,
  },
  {
    id: "2",
    conversation_id: "1",
    sender_id: "demo-user-123",
    content: "Great! They're still available. When can you meet?",
    created_at: new Date(Date.now() - 2.5 * 60 * 60 * 1000).toISOString(),
    is_read: true,
  },
  {
    id: "3",
    conversation_id: "1",
    sender_id: "user-2",
    content: "Sounds good! See you at 3 PM",
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    is_read: true,
  },
]
